name: Deploy and Test k3d Cluster

on:
  #push:
  #  branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-and-test-k3d:
    runs-on: ubuntu-latest
    steps:

      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: start-measurement

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Create k3d Cluster
        run: k3d cluster create ci-cluster --wait

      - name: Deploy application
        run: kubectl apply -f k8s/

      - name: Wait for Pods to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app=demo-db --timeout=180s
          kubectl wait --for=condition=ready pod -l app=petclinic --timeout=180s

      - name: Port-forward petclinic
        run: kubectl port-forward deploy/petclinic 8080:8080 &

      - name: Test petclinic health
        run: curl -f http://localhost:8080/actuator/health

      - name: Test demo-db health
        run: kubectl exec deploy/demo-db -- pg_isready || echo "Demo-DB test skipped"

      - name: Show Energy Results
        id: eco
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: display-results
          json-output: true

      - name: Print total data JSON
        run: |
          echo "Total data JSON: ${{ steps.eco.outputs.data-total-json }}"

      - name: Upload total-data.json
        uses: actions/upload-artifact@v4
        with:
          name: eco-ci-total-data-k3d-deploy-and-test
          path: /tmp/eco-ci/total-data.json
          retention-days: 30
