name: Deploy and Test Cluster

on:
  push:
    branches: [main]
    #paths:
    #  - 'k8s/**'
  pull_request:
    branches: [main]
    #paths:
    #  - 'k8s/**'

jobs:
  deploy-and-test-cluster:
    runs-on: ubuntu-latest
    steps:

      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: start-measurement

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Deploy application
        run: |
          kubectl apply -f k8s/

      - name: Wait for Pods to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app=demo-db --timeout=180s
          kubectl wait --for=condition=ready pod -l app=petclinic --timeout=180s

      - name: Port-forward petclinic
        run: kubectl port-forward deploy/petclinic 8080:8080 &


      - name: Test petclinic health
        run: curl -f http://localhost:8080/actuator/health

      - name: Test demo-db health
        run: kubectl exec deploy/demo-db -- pg_isready || echo "Demo-DB test skipped"

      - name: Show Energy Results
        id: eco
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: display-results
          json-output: true

      - name: Print total data JSON
        run: |
          echo "Total data JSON: ${{ steps.eco.outputs.data-total-json }}"

      - name: Upload total-data.json
        uses: actions/upload-artifact@v4
        with:
          name: eco-ci-total-data-k8s-deploy-and-test
          path: /tmp/eco-ci/total-data.json

