name: Deploy and Test MicroK8s Cluster
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-and-test-microk8s:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: start-measurement

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install MicroK8s
        run: |
          sudo snap install microk8s --classic --channel=1.28/stable
          sudo microk8s status --wait-ready

      - name: Enable MicroK8s Addons
        run: sudo microk8s enable dns storage

      - name: Deploy Application
        run: sudo microk8s kubectl apply -f k8s/

      - name: Wait for Pods to be Ready
        run: |
          sudo microk8s kubectl wait --for=condition=ready pod -l app=demo-db --timeout=180s
          sudo microk8s kubectl wait --for=condition=ready pod -l app=petclinic --timeout=180s

      - name: Port-forward PetClinic
        run: sudo microk8s kubectl port-forward deploy/petclinic 8080:8080 &

      - name: Test PetClinic Health
        run: |
          # Wait a moment for port-forward to establish
          sleep 5
          sudo microk8s kubectl exec deploy/petclinic -- curl -f http://localhost:8080/actuator/health

      - name: Test Demo-DB Health
        run: sudo microk8s kubectl exec deploy/demo-db -- pg_isready || echo "Demo-DB test skipped"

      - name: Show Energy Results
        id: eco
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: display-results
          json-output: true

      - name: Print Total Data JSON
        run: |
          echo "Total data JSON: ${{ steps.eco.outputs.data-total-json }}"

      - name: Upload total-data.json
        uses: actions/upload-artifact@v4
        with:
          name: eco-ci-total-data-microk8s-deploy-and-test
          path: /tmp/eco-ci/total-data.json
          retention-days: 30