name: Java CI with Gradle (Debian)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest        # Ubuntu runner is required; container will be Debian
    container:
      image: debian:12            # Use Debian 12 container
    strategy:
      matrix:
        java: [ '17' ] #, '21' ]
        distribution: [ 'temurin' ] #, 'corretto', 'zulu', 'liberica', 'microsoft' ]
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: start-measurement

      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y wget unzip git curl software-properties-common

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}

      - name: Setup Gradle
        run: |
          GRADLE_VERSION=8.4
          wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip -P /tmp
          unzip -d /opt/gradle /tmp/gradle-$GRADLE_VERSION-bin.zip
          echo "PATH=/opt/gradle/gradle-$GRADLE_VERSION/bin:$PATH" >> $GITHUB_ENV
          gradle -v

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Get Build Measurement
        id: total-measurement-step
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: get-measurement
          label: 'Build gradle debian'

      - name: Show Energy Results
        id: eco
        uses: green-coding-solutions/eco-ci-ene
