name: Java CI with Gradle (Debian)

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Install JDK and Gradle
        run: |
          apt-get update
          apt-get install -y wget unzip git curl
          # Install OpenJDK 17
          apt-get install -y openjdk-17-jdk
          # Verify Java
          java -version
          javac -version
          # Install Gradle manually (if you want latest)
          GRADLE_VERSION=8.4
          wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip -P /tmp
          unzip -d /opt/gradle /tmp/gradle-$GRADLE_VERSION-bin.zip
          echo 'export PATH=/opt/gradle/gradle-8.4/bin:$PATH' >> $GITHUB_ENV
          gradle -v
      # continue with your build steps

      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: start-measurement

      - uses: actions/checkout@v4

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with: 
          java-version: ${{matrix.java}}
          distribution: ${{ matrix.distribution }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Get Build Measurement
        id: total-measurement-step
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: get-measurement
          label: 'Build gradle debian' 
          
      - name: Show Energy Results
        id: eco
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: display-results
          json-output: true

      - name: Print total data JSON
        run: |
          echo "Total data JSON: ${{ steps.eco.outputs.data-total-json }}"

      - name: Upload total-data.json
        uses: actions/upload-artifact@v4
        with:
          name: eco-ci-total-data-gradle-${{ matrix.java }}-${{ matrix.distribution }}
          path: /tmp/eco-ci/total-data.json
          retention-days: 30
