
# Java CI with Javac on Alpine  
name: Java CI with Javac Alpine
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache git curl bash maven
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      # Use Maven to fetch dependencies (without building the project)
      - name: Download dependencies
        run: ./mvnw dependency:copy-dependencies -DoutputDirectory=libs -DincludeScope=runtime
      - name: Compile with javac
        run: |
          mkdir -p build/classes
          find src/main/java -name "*.java" > sources.txt
          javac -d build/classes -cp "libs/*" @sources.txt