name: Java CI with Maven on Alpine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17-jdk-alpine  # Alpine with JDK
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache bash git coreutils go g++ make cmake python3 py3-pip

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: start-measurement

      - name: Build with Maven Wrapper
        run: ./mvnw -B compile package -DskipTests

      - name: Get Build Measurement
        id: total-measurement-step
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: get-measurement
          label: 'Build Maven Alpine'

      - name: Show Energy Results
        id: eco
        uses: green-coding-solutions/eco-ci-energy-estimation@v3
        with:
          task: display-results
          json-output: true

      - name: Print total data JSON
        run: |
          echo "Total data JSON: ${{ steps.eco.outputs.data-total-json }}"

      - name: Upload total-data.json
        uses: actions/upload-artifact@v4
        with:
          name: eco-ci-total-data
          path: /tmp/eco-ci/total-data.json
