# Java CI with Maven on Alpine
name: Java CI with Maven Alpine
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17-jdk-alpine
    strategy:
      matrix:
        java: [ '17' ]
    steps:

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache git bash python3 py3-pip py3-virtualenv coreutils go
          # Ensure bash is in /usr/bin for GitHub Actions
          ln -sf /bin/bash /usr/bin/bash
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip

      - name: Create Python virtualenv
        run: |
          python3 -m venv /tmp/eco-ci/venv
          source /tmp/eco-ci/venv/bin/activate
          pip install --upgrade pip
          echo "Virtualenv created at /tmp/eco-ci/venv"

      - name: Checkout eco-ci action code
        run: |
          mkdir -p /home/runner/work/_actions/green-coding-solutions/
          git clone --depth 1 --branch v3 https://github.com/green-coding-solutions/eco-ci-energy-estimation.git \
            /home/runner/work/_actions/green-coding-solutions/eco-ci-energy-estimation/v3

      - name: Initialize eco-ci
        run: |
          source /tmp/eco-ci/venv/bin/activate
          /home/runner/work/_actions/green-coding-solutions/eco-ci-energy-estimation/v3/scripts/setup.sh initialize -g true


      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: start-measurement
      
      - name: Preparatory Tasks Measure
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: get-measurement
          label: 'Preparatory Tasks Measure'

      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Build with Maven Wrapper
        run: ./mvnw -B compile package -DskipTests

      - name: Get Build Measurement
        id: total-measurement-step
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: get-measurement
          label: 'Build maven alpine'

      - name: Show Energy Results
        id: eco
        uses: green-coding-solutions/eco-ci-energy-estimation@v3 # use hash or @vX here (See note below)
        with:
          task: display-results
          json-output: true

      - name: Print total data JSON
        run: |
          echo "Total data JSON: ${{ steps.eco.outputs.data-total-json }}"

      - name: Upload total-data.json
        uses: actions/upload-artifact@v4
        with:
          name: eco-ci-total-data
          path: /tmp/eco-ci/total-data.json