name: Java CI with Maven on Alpine + eco-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17-jdk-alpine  # Alpine with JDK
    steps:
      - uses: actions/checkout@v4

      # Install system dependencies
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache bash git coreutils go g++ make cmake python3 py3-pip
          python3 -m ensurepip
          python3 -m pip install --upgrade pip

      # Make Maven wrapper executable
      - name: Make mvnw executable
        run: chmod +x ./mvnw

      # Clone eco-ci repo
      - name: Clone eco-ci repo
        run: |
          git clone --depth 1 --branch v3 https://github.com/green-coding-solutions/eco-ci-energy-estimation.git eco-ci
          chmod +x eco-ci/scripts/setup.sh

      # Initialize eco-ci measurement
      - name: Initialize eco-ci
        run: ./eco-ci/scripts/setup.sh initialize -g true

      # Start eco-ci measurement
      - name: Start Measurement
        run: python3 eco-ci/scripts/measurement.py start --branch main --send-data true

      # Build Maven project
      - name: Build with Maven Wrapper
        run: ./mvnw -B compile package -DskipTests

      # Get eco-ci measurement after build
      - name: Get Build Measurement
        run: python3 eco-ci/scripts/measurement.py get --label "Build Maven Alpine"

      # Display eco-ci results
      - name: Show Energy Results
        run: python3 eco-ci/scripts/measurement.py display --json-output true

      # Upload JSON artifact
      - name: Upload total-data.json
        uses: actions/upload-artifact@v4
        with:
          name: eco-ci-total-data
          path: eco-ci/total-data.json
