# Java CI with Maven on Alpine
name: Java CI with Maven Alpine
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache git curl bash openjdk17 maven
      - uses: actions/checkout@v4
      - name: Set JAVA_HOME
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Build with Maven Wrapper
        run: ./mvnw -B verify